config/routes.rb
Rails.application.routes.draw do
  resources :kittens
  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:notice] = "Kitten successfully created!"
      redirect_to @kitten
    else
      render :new
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @kitten }
    end

  end

  def index
    @kittens = Kitten.all.order("created_at DESC")

    respond_to do |format|
      format.html
      format.js
      format.json { render json: @kittens }
    end

  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:notice] = "Kitten updated!"
      redirect_to @kitten
    else
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:notice] = "Kitten has been deleted!"
    redirect_to root_path
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten, remote: true do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  </br></br>
  <%= f.label :age, "Age" %>
  <%= f.text_field :age %>
  </br></br>
  <%= f.label :cuteness, "Cuteness"%>
  <%= f.select( :cuteness, 1..10.times { |i| i + 1} ) %>
  </br></br>
  <%= f.label :softness, "Softness"%>
  <%= f.select( :softness, 1..10.times { |i| i + 1} ) %>
  </br></br>
  <%= f.submit :submit, name: nil%>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "form" %>

</br>
<%= link_to  "Home", root_path %>
<%= link_to  "Delete", @kitten, method: :delete, confirm: "Are you sure?" %>

app/views/kittens/index.html.erb
<h1>All Kittens</h1>

<%= link_to  "New Kitten", new_kitten_path %>
</br></br>

<% @kittens.each do |cat| %>
  <%= link_to  cat.name, cat %>
  </br>
<% end %>

app/views/kittens/new.html.erb
<h1>New Kitten!</h1>

<%= render "form" %>

app/views/kittens/show.html.erb
<h1>Kitten!</h1>

<table>
<tr>
  <td>Name:</td>
  <td><%= @kitten.name %></td>
</tr>
<tr>
  <td>Age:</td>
  <td><%= @kitten.age%></td>
</tr>
<tr>
  <td>Cuteness:</td>
  <td><%= @kitten.cuteness%></td>
</tr>
<tr>
  <td>Softness</td>
  <td><%= @kitten.softness%></td>
</tr>
</table>

</br>
<%= link_to  "Home", root_path %>
<%= link_to  "Edit", edit_kitten_path %>
<%= link_to  "Delete", @kitten, method: :delete, confirm: "Are you sure?" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>